### PR TITLE
Manually create ProfilesViewModel in PreferencesController to avoid constructor cache issue in LoginCallbackFactory

### LINKED ISSUE #15099: Crash on opening Profiles-tab
When an active connection is established, opening the Profiles-tab results in application crash.

```
Type:        java.lang.IllegalArgumentException
Message:     
Source:      <DynamicMethodHolder>
Stack Trace: bei __<Invoker>(Object[] )
   bei Java_sun_reflect_ReflectionFactory.FastConstructorAccessorImpl.newInstance(Object[] args)
   bei java.lang.reflect.Constructor.newInstance(Object[] initargs, CallerID )
   bei ch.cyberduck.core.LoginCallbackFactory.create(Controller controller)
   bei ch.cyberduck.core.LoginCallbackFactory.get(Controller c)
   bei ch.cyberduck.core.SessionPoolFactory.create(Controller controller, Host bookmark, ProgressListener listener, Usage[] usage)
   bei ch.cyberduck.core.SessionPoolFactory.create(Controller controller, Host bookmark, ProgressListener listener)
   bei ch.cyberduck.core.SessionPoolFactory.create(Controller controller, Host bookmark)
   bei ch.cyberduck.core.profiles.ProfilesWorkerBackgroundAction..ctor(Controller controller, ProfilesSynchronizeWorker worker)
   bei Ch.Cyberduck.Core.Refresh.ViewModels.Preferences.Pages.ProfilesViewModel.<>c__DisplayClass4_0.<<-ctor>b__0>d.MoveNext() in W:\iterate\cyberduck\core\native\refresh\src\main\csharp\ViewModels\Preferences\Pages\ProfilesViewModel.cs:Zeile 39.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Reactive.Subjects.AsyncSubject`1.GetResult() in /_/Rx.NET/Source/src/System.Reactive/Subjects/AsyncSubject.cs:Zeile 432.
   bei Ch.Cyberduck.Core.Refresh.ReactiveMixins.<>c__DisplayClass0_0`2.<<ExecuteIfPossible>b__1>d.MoveNext() in W:\iterate\cyberduck\core\native\refresh\src\main\csharp\ReactiveMixins.cs:Zeile 11.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   bei System.Windows.Threading.DispatcherOperation.InvokeImpl()
   bei MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Windows.Threading.DispatcherOperation.Invoke()
   bei System.Windows.Threading.Dispatcher.ProcessQueue()
   bei System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   bei MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   bei System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   bei System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   bei System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   bei System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   bei Ch.Cyberduck.Ui.Program.Main(String[] args) in W:\iterate\cyberduck\windows\src\main\csharp\ch\cyberduck\ui\Program.cs:Zeile 101.
```

### PR DESCRIPTION
**Pull request by AliveDevil**
Fixes #15099

### CODE REVIEW

File: core/src/test/java/ch/cyberduck/core/LoginCallbackFactoryTest.java [hunk 1]
```diff
@@ -32,4 +40,60 @@ public void invoke(final MainAction runnable, final boolean wait) {
             }
         }));
     }
+
+    @Test
+    @Ignore
```
Comment (AliveDevil) [inline core/src/test/java/ch/cyberduck/core/LoginCallbackFactoryTest.java:45]: Ignored, because either intended, or exceptional.
If exceptional, this should be fixed, otherwise keep as ignored, to make communicate, that this behavior is intended.

Comment (dkocher) [reply core/src/test/java/ch/cyberduck/core/LoginCallbackFactoryTest.java]: Can changes in f92b8a300820b481cc6f49a64d18f0ba85379f7d be reverted with removed constructor caching in f2f8abb2ce4e6a066719ab7c253454975fb88e96?

Comment (AliveDevil) [reply core/src/test/java/ch/cyberduck/core/LoginCallbackFactoryTest.java]: Don't know what the performance implication here is. Reflection is slow.

Comment (dkocher) [reply core/src/test/java/ch/cyberduck/core/LoginCallbackFactoryTest.java]: These callbacks are not requested frequently that it would have any noticeable performance implication.

Comment (AliveDevil) [reply core/src/test/java/ch/cyberduck/core/LoginCallbackFactoryTest.java]: The change in f92b8a3 can't be reverted, as the LoginCallback requires a WindowController in its constructor, which the BaseController (which is registered in the DI Container) is not a subtype of, thus DisabledLoginCallback would be used for the profiles fetcher (and a warning logged).

Comment (dkocher) [reply core/src/test/java/ch/cyberduck/core/LoginCallbackFactoryTest.java]: Loading profiles will require no login and thus it is not a problem if `DisabledLoginCallback` is used.

Comment (AliveDevil) [reply core/src/test/java/ch/cyberduck/core/LoginCallbackFactoryTest.java]: Will check what I can do to get f92b8a3 reverted.

Comment (AliveDevil) [reply core/src/test/java/ch/cyberduck/core/LoginCallbackFactoryTest.java]: Can the log.warn in the callback factories be gated behind log.isDebugEnabled?

Comment (dkocher) [reply core/src/test/java/ch/cyberduck/core/LoginCallbackFactoryTest.java]: The log statement doesn't do any harm.

**Comment by AliveDevil** [comment]
I don't get this test failure.

Works on Windows and macOS, but fails on Linux?
>  LoginCallbackFactoryTest.testCreateOrder:49 expected:<class ch.cyberduck.core.LoginCallbackFactoryTest$TestLoginCallback> but was:<class ch.cyberduck.core.DisabledLoginCallback>

Why should it fail on Linux only.

**Comment by AliveDevil** [comment]
Test failure is runtime dependent. Some other test runs before that and creates a LoginCallbackFactory with Preference set to factory.logincallback.class=Disabled

Which then results in subsequent test runs to return wrong classes. Fixing.

File: core/src/test/java/ch/cyberduck/core/LoginCallbackFactoryTest.java
Comment (AliveDevil) [inline core/src/test/java/ch/cyberduck/core/LoginCallbackFactoryTest.java:1]: @dkocher LoginCallbackFactorys singleton, and order of execution on this specific test (first testCreate(), then testCreateOrder()) results in the singleton being created for "DisabledLoginCallbackFactory", which fails in testCreateOrder, because the LoginCallbackFactory is not side-effect free.

**Review by dkocher — APPROVED** [review]
