### PR TITLE
Fix SystemLocal sanitization

### LINKED ISSUE #13933: Crash on Windows 11 Pro with IdentityAgent in ssh config
**Describe the bug**
Since version 8.3.0 in April, Cyberduck crashes on launch with my ssh config file. I originally thought my problem was #13672, but after realizing the fix for that was supposed to have been released already, I actually checked my crash reports and narrowed this down today. As of 8.4.5.38423 and 8.5.1.38745, the problem goes away if I comment out my IdentityAgent line. Fortunately, I don't think I actually need it - I don't use the SSH agent, so the following ProxyCommand line, which doesn't cause me any problems, is the important one.

**To Reproduce**
1. Have an ssh config with a line that starts with `IdentityAgent //` 
2. Try to launch Cyberduck

If the next character of the IdentityAgent is a period, the program crashes. If it is anything else, it seems to hang indefinitely with a process running but the UI never appears.

The reason I had the configuration in question was because Krypton Authenticator adds the following (path redacted):

```
# Added by Krypton
Host *
	IdentityAgent \\.\pipe\krd-agent
	ProxyCommand path\to\krssh.exe %h %p
```

but I had a _different_ tool - unfortunately I've forgotten what it was; it may have been a Visual Studio Code plugin - which worked if I changed the backslashes in the IdentityAgent line to forward slashes but not with the configuration as above.

Since I have a workaround, I've submitted this mostly in case it's a simple parsing issue that (A) is easy to fix and (2) might trip people up in a less obscure case. I may even come back later and try to whip up a pull request. My assumption is that the problem is in handling that kind of string in `LocalFactory.get()`, but I ran out of time to investigate this today before I figured out where LocalFactory lives in the codebase.

**Expected behavior**
Cyberduck working; if necessary, a convenient and documented way to tell Cyberduck not to try to parse my ssh config or to point it at a different one (which might already exist and I failed to find it...).

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro and Windows 11 Pro Insider Preview
 - Version: all attempts from at least 10.0.22593 through 10.0.25247

**Log Files**
[638055899217769141.txt](https://github.com/iterate-ch/cyberduck/files/10143983/638055899217769141.txt)

### PR DESCRIPTION
**Pull request by AliveDevil**

### CODE REVIEW

File: core/src/main/csharp/ch/cyberduck/core/local/SystemLocal.cs [hunk 1]
```diff
@@ -83,62 +82,119 @@ public override bool isSymbolicLink()
...
+                    char c = (char)reader.Read();
+                    if (c == Path.AltDirectorySeparatorChar || c == Path.DirectorySeparatorChar)
+                    {
+                        writer.Write(segmentBuilder.ToString().Trim());
+                        writer.Write(Path.DirectorySeparatorChar);
+                        segmentBuilder.Clear();
+                    }
+                    else if (Array.IndexOf(invalid, c) != -1)
+                    {
+                        segmentBuilder.Append('_');
```
Comment (AliveDevil) [inline core/src/main/csharp/ch/cyberduck/core/local/SystemLocal.cs:186]: @ylangisc Still UrlEncode invalid characters? Asof Windows 10 1803 '%'[^ms-docs] is a valid filename character. Thus rendering this invalid on any system which is not Windows 10 1803 (or newer, which is true for this[^commit] as well)
[^ms-docs]: https://learn.microsoft.com/troubleshoot/windows-client/networking/url-encoding-unc-paths-not-url-decoded
[^commit]: b169fcfbbbf2c3a9a2a9ca239dbe34d6db09347c

**Comment by dkocher** [comment]
Does this relate to #13723 as well?

**Comment by AliveDevil** [comment]
Fixes WSL drag/drop.
Next: UNC

**Comment by AliveDevil** [comment]
For Dragging onto UNC we'd need to implement IStorage[^IStorage], providing an enumeration of all Elements to be transferred.
[^IStorage]: https://learn.microsoft.com/en-us/windows/win32/api/objidl/nn-objidl-istorage

This must hook between Transfer#prepare (listing all files) and actually downloading files. Could we potentially just ignore the Transfer-window and directly drop into Background-processing for this scenario?

**Comment by dkocher** [comment]
> This must hook between Transfer#prepare (listing all files) and actually downloading files. Could we potentially just ignore the Transfer-window and directly drop into Background-processing for this scenario?

Could possibly be implemented as a `Bulk` [^1] feature.


[^1]: https://github.com/iterate-ch/cyberduck/blob/master/core/src/main/java/ch/cyberduck/core/features/Bulk.java

**Comment by AliveDevil** [comment]
Fix for #5330 is scheduled for later fix.

File: core/src/main/java/ch/cyberduck/core/transfer/download/AbstractDownloadFilter.java [hunk 2]
```diff
@@ -198,9 +196,9 @@ public TransferStatus prepare(final Path file, final Local local, final Transfer
                     // Free space on disk
                     long space = 0L;
                     try {
-                        space = Files.getFileStore(Paths.get(local.getParent().getAbsolute())).getUsableSpace();
+                        space = Paths.get(local.getParent().getAbsolute()).toFile().getUsableSpace();
```
Comment (dkocher) [inline core/src/main/java/ch/cyberduck/core/transfer/download/AbstractDownloadFilter.java:199]: Why is this change required?

**Review by dkocher — CHANGES_REQUESTED** [review]

File: core/src/main/java/ch/cyberduck/core/transfer/download/AbstractDownloadFilter.java (hunk 2 above)
Comment (AliveDevil) [reply core/src/main/java/ch/cyberduck/core/transfer/download/AbstractDownloadFilter.java:199]:
```
Files.getFileStore("\\…") == null
```
With `Paths.get().toFile()` we get access to the FileStore of that file, thus can see usablespace for remotes.

File: core/src/test/csharp/ch/cyberduck/core/local/SystemLocalTest.cs [hunk 3]
```diff
@@ -0,0 +1,43 @@
...
+        }
+
+        [Test]
+        public void TestWslPath()
+        {
+            CoreLocal local = new SystemLocal(WSL_PATH);
+            Assert.AreEqual(WSL_PATH, local.getAbsolute());
+        }
+    }
+}
```
[the remark this answers is not in the document]
Comment (AliveDevil) [reply core/src/test/csharp/ch/cyberduck/core/local/SystemLocalTest.cs:43]: Clarify `Path with disk label`.

[the remark this answers is not in the document]
Comment (dkocher) [reply core/src/test/csharp/ch/cyberduck/core/local/SystemLocalTest.cs:43]: `C:\absolute\path\to\file`

File: core/src/main/java/ch/cyberduck/core/transfer/download/AbstractDownloadFilter.java (hunk 2 above)
Comment (dkocher) [reply core/src/main/java/ch/cyberduck/core/transfer/download/AbstractDownloadFilter.java:199]: Do not understand your comment. It is about determining free disk space on the target volume.

Comment (AliveDevil) [reply core/src/main/java/ch/cyberduck/core/transfer/download/AbstractDownloadFilter.java:199]: Yes, correct. If downloading to a network drive/unc path in the future `Files.getFileStore` will result in `null` being returned.

That is: This will fail to determine disk space and disable segmented downloads to `\\wsl$`, `\\wsl.localhost`, `\\?\C:\Long\Path`.

**Review by dkocher — APPROVED** [review]

**Review by dkocher — APPROVED** [review]
