### PR TITLE
Do not use MLST when running with interoperability connection profile…

### LINKED ISSUE #14333: Ftp MLST used despite compatibility protocol (FTP)
**Describe the bug**
I'm trying to upload the folder containing other folders and files via FTP. According to the logs there's an issue with the `250-Status` response, maybe it's wrongly sent by the server. Testing with a different FTP client worked, though.

**Screenshots**
Attached screenshots of the ftpd server.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 13.2.1

**Log Files**
[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/10930743/cyberduck.log)

**Additional context**
IMG_B948C8971E7B-1

### PR DESCRIPTION
**Pull request by dkocher**
…. Fix #14333.

### CODE REVIEW

File: ftp/src/main/java/ch/cyberduck/core/ftp/FTPAttributesFinderFeature.java [hunk 1]
```diff
@@ -56,18 +58,21 @@ public PathAttributes find(final Path file, final ListProgressListener listener)
...
-                    if(!FTPReply.isPositiveCompletion(session.getClient().sendCommand(FTPCmd.MLST, file.getAbsolute()))) {
-                        throw new FTPException(session.getClient().getReplyCode(), session.getClient().getReplyString());
-                    }
-                    final FTPDataResponseReader reader = new FTPMlsdListResponseReader();
-                    final AttributedList<Path> attributes
-                            = reader.read(file.getParent(), Arrays.asList(session.getClient().getReplyStrings()), listener);
-                    if(attributes.contains(file)) {
-                        return attributes.get(attributes.indexOf(file)).attributes();
+                final PreferencesReader preferences = new HostPreferences(session.getHost());
+                if(preferences.getBoolean("ftp.command.mlsd")) {
```
Comment (ylangisc) [inline ftp/src/main/java/ch/cyberduck/core/ftp/FTPAttributesFinderFeature.java:62]: Explicit property to avoid confusion `mlsd` vs. `mslt`?

Comment (dkocher) [reply ftp/src/main/java/ch/cyberduck/core/ftp/FTPAttributesFinderFeature.java:62]: Thus just keep it as is.

**Review by ylangisc — APPROVED** [review]
