### PR TITLE
No need to decode prefixes.

### LINKED ISSUE #14521: Improper prefix handling when versioning is disabled
Folders created with special characters such as `+` are properly created on remote storage but listing shows a space due to unnecessary URI decoding. Regression from 9678553e3781744d8fbcc15dd2e9e6606dc7b72e.

### PR DESCRIPTION
**Pull request by ylangisc**
Fixes #14521

### CODE REVIEW

File: googlestorage/src/test/java/ch/cyberduck/core/googlestorage/GoogleStorageObjectListServiceTest.java [hunk 1]
```diff
@@ -99,6 +100,27 @@ public void testListEncodedCharacter() throws Exception {
...
+        container.attributes().setRegion("us-east-1");
+        final Path placeholder = new GoogleStorageDirectoryFeature(session).mkdir(
+                new Path(container, String.format("%s +", new AlphanumericRandomStringService().random()), EnumSet.of(Path.Type.directory)), new TransferStatus());
+        assertTrue(new GoogleStorageObjectListService(session).list(container, new DisabledListProgressListener()).contains(placeholder));
+        new GoogleStorageDeleteFeature(session).delete(Collections.singletonList(placeholder), new DisabledLoginCallback(), new Delete.DisabledCallback());
+    }
+
+    @Test
+    public void testListEncodedCharacterFolderNonVersioned() throws Exception {
+        PreferencesFactory.get().setProperty("googlestorage.listing.versioning.enable", false);
```
Comment (dkocher) [inline googlestorage/src/test/java/ch/cyberduck/core/googlestorage/GoogleStorageObjectListServiceTest.java:115]: This will affect other tests.

**Review by dkocher — CHANGES_REQUESTED** [review]

**Review by dkocher — APPROVED** [review]
