### PR TITLE
Fix #17484.

### LINKED ISSUE #17484: Ceph RadosGW S3 bucket name incompatibility
When running Ceph RadosGW with both S3, and Swift API exposed there's an incompatibility with Bucket Naming schemes.
Specifically, Swift allows S3 DNS invalid bucket names, like "Abc Test", which work fine in Swift, and are returned correctly to Cyberduck (they are listed, afterall).
But, trying to access these results in 
```
2025-09-18 14:42:42,812 [timer-1] ERROR ch.cyberduck.core.shared.ThreadPoolSchedulerFeature - Failure processing scheduled task Illegal character in path at index 23: http://s3.lab.xc:80/asd test/?location=
java.lang.IllegalArgumentException: Illegal character in path at index 23: http://s3.lab.xc:80/asd test/?location=
	at java.net.URI.create(URI.java:850)
	at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:66)
	at ch.cyberduck.core.s3.RequestEntityRestStorageService.setupConnection(RequestEntityRestStorageService.java:249)
	at org.jets3t.service.impl.rest.httpclient.RestStorageService.performRestGet(RestStorageService.java:1076)
	at ch.cyberduck.core.s3.RequestEntityRestStorageService.performRestGet(RequestEntityRestStorageService.java:400)
	at org.jets3t.service.impl.rest.httpclient.RestStorageService.performRestGet(RestStorageService.java:1055)
	at org.jets3t.service.impl.rest.httpclient.RestStorageService.getBucketLocationImpl(RestStorageService.java:1784)
	at org.jets3t.service.impl.rest.httpclient.RestS3Service.getBucketLocationImpl(RestS3Service.java:619)
	at org.jets3t.service.S3Service.getBucketLocation(S3Service.java:3095)
	at ch.cyberduck.core.s3.S3LocationFeature.getLocation(S3LocationFeature.java:92)
	at ch.cyberduck.core.s3.S3LocationFeature.getLocation(S3LocationFeature.java:75)
	at ch.cyberduck.core.cloudfront.CloudFrontDistributionConfiguration.getRegion(CloudFrontDistributionConfiguration.java:638)
	at ch.cyberduck.core.cloudfront.CloudFrontDistributionConfiguration.client(CloudFrontDistributionConfiguration.java:621)
	at ch.cyberduck.core.cloudfront.CloudFrontDistributionConfiguration.read(CloudFrontDistributionConfiguration.java:119)
	at ch.cyberduck.core.s3.S3Session$1.read(S3Session.java:117)
	at ch.cyberduck.core.cloudfront.CloudFrontDistributionConfigurationPreloader.operate(CloudFrontDistributionConfigurationPreloader.java:60)
	at ch.cyberduck.core.cloudfront.CloudFrontDistributionConfigurationPreloader.operate(CloudFrontDistributionConfigurationPreloader.java:38)
	at ch.cyberduck.core.shared.ThreadPoolSchedulerFeature$FailureAwareRunnable.run(ThreadPoolSchedulerFeature.java:68)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:512)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:625)
	at ch.cyberduck.core.threading.NamedThreadFactory$1.run(NamedThreadFactory.java:57)
	at java.lang.Thread.run(Thread.java:980)
Caused by: java.net.URISyntaxException: Illegal character in path at index 23: http://s3.lab.xc:80/asd test/?location=
	at java.net.URI$Parser.fail(URI.java:2847)
	at java.net.URI$Parser.checkChars(URI.java:3020)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3052)
	at java.net.URI.<init>(URI.java:589)
	... 26 more
```

The RadosGW S3 endpoint returns the bucket without issue:
```
curl -I "http://s3.lab.xc/asd%20test"
HTTP/1.1 403 Forbidden
Content-Length: 247
x-amz-request-id: tx0000061cd95eaf926437e-0068cbff70-569867018-default
Accept-Ranges: bytes
Content-Type: application/xml
Server: Ceph Object Gateway (squid)
Date: Thu, 18 Sep 2025 12:47:44 GMT
Connection: Keep-Alive
```
From this perspective, our S3 implementation should path-encode the bucket name, when it's not used with bucket DNS endpoints.

### PR DESCRIPTION
**Pull request by dkocher**

### CODE REVIEW

**Comment by AliveDevil** [comment]
```
Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 24: http://host:80/test space/?versioning
	at java.net.URI.create(URI.java:850)
	at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:66)
	at ch.cyberduck.core.s3.RequestEntityRestStorageService.setupConnection(RequestEntityRestStorageService.java:255)
	at org.jets3t.service.impl.rest.httpclient.RestStorageService.performRestGet(RestStorageService.java:1076)
	at ch.cyberduck.core.s3.RequestEntityRestStorageService.performRestGet(RequestEntityRestStorageService.java:406)
	at org.jets3t.service.impl.rest.httpclient.RestStorageService.performRestGet(RestStorageService.java:1055)
	at org.jets3t.service.impl.rest.httpclient.RestS3Service.getBucketVersioningStatusImpl(RestS3Service.java:491)
	at org.jets3t.service.S3Service.getBucketVersioningStatus(S3Service.java:2174)
	at ch.cyberduck.core.s3.S3VersioningFeature.getConfiguration(S3VersioningFeature.java:137)
	at ch.cyberduck.core.vault.registry.VaultRegistryVersioningFeature.getConfiguration(VaultRegistryVersioningFeature.java:46)
	at ch.cyberduck.core.s3.S3ListService.listObjects(S3ListService.java:82)
	at ch.cyberduck.core.s3.S3ListService.list(S3ListService.java:75)
```
Same for ACL, Versions, Logging.

**Comment by AliveDevil** [comment]
Regular transfers work fine, only the presigned url provider has issues with it, though I don't see an easy way to fix it.
```
Top-level Exception
Type:        java.lang.RuntimeException
Message:     java.net.URISyntaxException: Illegal character in path at index 22: https://host/test space/%2375.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=S5HXEYO2W2WNJ08B57PW/20260209/default/s3/aws4_request&X-Amz-Date=20260209T153831Z&X-Amz-Expires=3590&X-Amz-SignedHeaders=host
Source:      Cyberduck.Core
Stack Trace: bei org.jets3t.service.S3Service.createSignedUrlUsingSignatureVersion(String requestSignatureVersion, String region, String method, String bucketName, String objectKey, String specialParamName, Map headersMap, Int64 secondsSinceEpoch, Boolean isVirtualHost, Boolean isHttps, Boolean isDnsBucketNamingDisabled)
   bei ch.cyberduck.core.s3.S3PresignedUrlProvider.create(Credentials credentials, String bucket, String region, String key, String method, Int64 expiry)
   bei ch.cyberduck.core.s3.S3UrlProvider.PresignedUrl.getUrl()
```

File: s3/src/main/java/ch/cyberduck/core/s3/RequestEntityRestStorageService.java [hunk 1]
```diff
@@ -134,6 +134,16 @@ protected void initializeProxy(final HttpClientBuilder httpClientBuilder) {
         //
     }
 
+    @Override
+    public String createSignedUrlUsingSignatureVersion(final String requestSignatureVersion,
```
Comment (AliveDevil) [inline s3/src/main/java/ch/cyberduck/core/s3/RequestEntityRestStorageService.java]: This won't be called, as the S3PresignedUrlProvider uses a custom implementation: https://github.com/iterate-ch/cyberduck/blob/02265bb30227fdc51090a3a8fd7a1aabdc0edb90/s3/src/main/java/ch/cyberduck/core/s3/S3PresignedUrlProvider.java#L59

**Review by AliveDevil — APPROVED** [review]
