### PR TITLE
Prioritise password authentication if one is set.

### LINKED ISSUE #13442: Unable to connect via SFTP
**Describe the bug**

Connecting via SFTP with password authentication fails. Cyberduck tries to authenticate via public key.
This is happening for Cyberduck version 8+. The issue is not present in Cyberduck 7.10.2.

**To Reproduce**
1. Create new SFTP connection bookmark
2. Setup authentication via password
3. Set SSH Private Key as "None"
4. Double click the bookmark to connect
5. The connection attempt is rejected, UI shows an error message:
> **Connection failed**
> Application error. The connection attempt was rejected. The server may be down, or your network may not be properly configured.

**Expected behavior**
Connection should not fail.
I was told by my hosting provider the client is trying to connect using public key however it is configured to use password instead. Cyberduck should authenticate using password.

**Screenshots**
Screenshot 2022-06-08 at 00 31 11

**Desktop:**
 - OS: macOS Catalina 10.15.7
 - Version 8.3.3 (also tried with versions 8.2.3 and 8.0.0)

**Log Files**
*Note:* The domain was replaced with `example.com` in all logs.

Related Cyberduck log:
```
2022-06-08 00:16:40,223 [sshj-Reader-example.com/37.9.175.156:22] DEBUG net.schmizz.sshj.transport.kex.Curve25519SHA256 - Sending SSH_MSG_KEXDH_INIT
2022-06-08 00:16:40,244 [sshj-Reader-example.com/37.9.175.156:22] INFO  net.schmizz.sshj.transport.TransportImpl - Received SSH_MSG_DISCONNECT (reason=BY_APPLICATION, msg=Application error)
2022-06-08 00:16:40,244 [sshj-Reader-example.com/37.9.175.156:22] ERROR net.schmizz.sshj.transport.TransportImpl - Dying because - Application error
net.schmizz.sshj.transport.TransportException: Application error
	at net.schmizz.sshj.transport.TransportImpl.gotDisconnect(TransportImpl.java:533) ~[sshj-0.33.0.jar:?]
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:489) ~[sshj-0.33.0.jar:?]
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:113) ~[sshj-0.33.0.jar:?]
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:200) ~[sshj-0.33.0.jar:?]
	at net.schmizz.sshj.transport.Reader.run(Reader.java:60) ~[sshj-0.33.0.jar:?]
```
Full log here: [cyberduck.log](https://github.com/iterate-ch/cyberduck/files/8856937/cyberduck.log)

Related log from hosting provider:
```
USER [example.com](http://example.com/) (Login failed): authentication via 'ssh-rsa' public key failed
```

**Additional context**
I can connect via `sftp` command line without any issues, therefore I can rule out general network issues.

**Workaround**
Downgrading all the way down to Cyberduck version 7.10.2 works fine.

### PR DESCRIPTION
**Pull request by ylangisc**
Reduces number of authentications if an explicit password is set. Fixes #13442. Relates to #13680 to minimize authentication attempts.

### CODE REVIEW

File: ssh/src/main/java/ch/cyberduck/core/sftp/SFTPSession.java [hunk 1]
```diff
@@ -308,7 +308,12 @@ private void authenticate(final SSHClient client, final Host host, final LoginCa
         }
         defaultMethods.add(new SFTPPublicKeyAuthentication(client));
         defaultMethods.add(new SFTPChallengeResponseAuthentication(client));
-        defaultMethods.add(new SFTPPasswordAuthentication(client));
+        if(host.getCredentials().isPasswordAuthentication()) {
```
Comment (dkocher) [inline ssh/src/main/java/ch/cyberduck/core/sftp/SFTPSession.java:311]: There is already local variable `credentials` in scope.

**Review by dkocher — APPROVED** [review]
