### PR TITLE
If there is an explicit key set in bookmark try to filter ssh agent i…

### LINKED ISSUE #13680: Prioritize identity set in bookmark before enumerating
There are servers disconnecting users after one failed authentication attempt.
Using SFTP Agent authentication can result in numerous failing attempts.

Is there a way where we can sort the list of identities found by priority (identity set in bookmark first, then all others)?

### PR DESCRIPTION
**Pull request by ylangisc**
…dentities based on the comment field which normally contains the key path. Resolves #13680.

### CODE REVIEW

File: ssh/src/main/java/ch/cyberduck/core/sftp/auth/SFTPAgentAuthentication.java [hunk 1]
```diff
@@ -74,4 +80,21 @@ public Boolean authenticate(final Host bookmark, final LoginCallback prompt, fin
...
+            final Collection<Identity> candidates = new ArrayList<>();
+            for(Identity identity : identities) {
+                if(identity.getComment() != null) {
+                    if(selected.getAbsolute().equals(new String(identity.getComment(), StandardCharsets.UTF_8))) {
+                        return Collections.singletonList(identity);
+                    }
+                }
+                candidates.add(identity);
+            }
+            return candidates;
```
Comment (dkocher) [inline ssh/src/main/java/ch/cyberduck/core/sftp/auth/SFTPAgentAuthentication.java:96]: Same as returning original set `identities`?

File: ssh/src/main/java/ch/cyberduck/core/sftp/auth/SFTPAgentAuthentication.java [hunk 2]
```diff
@@ -74,4 +80,21 @@ public Boolean authenticate(final Host bookmark, final LoginCallback prompt, fin
...
     }
+
+    protected Collection<Identity> filterIdentities(final Host bookmark, final Collection<Identity> identities) {
+        if(bookmark.getCredentials().isPublicKeyAuthentication()) {
+            final Local selected = bookmark.getCredentials().getIdentity();
+            final Collection<Identity> candidates = new ArrayList<>();
+            for(Identity identity : identities) {
+                if(identity.getComment() != null) {
+                    if(selected.getAbsolute().equals(new String(identity.getComment(), StandardCharsets.UTF_8))) {
+                        return Collections.singletonList(identity);
```
Comment (dkocher) [inline ssh/src/main/java/ch/cyberduck/core/sftp/auth/SFTPAgentAuthentication.java:91]: Add log statement that only a single key from SSH agent is selected.

**Review by dkocher — CHANGES_REQUESTED** [review]

**Review by dkocher — APPROVED** [review]
