### PR TITLE
Notify TransfersWindow to reveal an item

### LINKED ISSUE #16073: Transfer window opens completely scrolled to the top
**Describe the bug**
Transfer window opens completely scrolled to the top so that only the old transfers are visible.

**Expected behavior**
Open Transfer window with focus on the current transfer.

**Desktop (please complete the following information):**
 - OS: Windows
 - Cyberduck Version 9

### PR DESCRIPTION
**Pull request by AliveDevil**
Fixes #16073

### CODE REVIEW

File: windows/src/main/csharp/ch/cyberduck/ui/ViewModels/TransfersViewModel.cs [hunk 1]
```diff
@@ -233,8 +234,12 @@ public bool ToolbarSeparatorRight
         var transfersCache = store.Transfers.Connect().ObserveOnDispatcher()
             .Transform(m => new TransferViewModel(controller, m, locale)).DisposeMany()
             .Bind(out transfers).AsObservableCache().DisposeWith(subscriptions);
-        subscriptions.Add(transfersCache.Connect().Subscribe(OnTransfersChanged));
         subscriptions.Add(transfersCache.CountChanged.Subscribe(OnTransfersCountChanged));
+        subscriptions.Add(Observable.FromEvent<Transfer>(
+            h => controller.RevealTransfer += h,
+            h => controller.RevealTransfer -= h)
+            .Select(transfersCache.WatchValue).Switch()
```
Comment (AliveDevil) [inline windows/src/main/csharp/ch/cyberduck/ui/ViewModels/TransfersViewModel.cs:241]: If transfersCache doesn't have Transfer cached, with Lookup would return `Optional.None`.
This guarantees that a valid value is passed on.

File: windows/src/main/csharp/ch/cyberduck/ui/ViewModels/TransfersViewModel.cs [hunk 2]
```diff
@@ -233,8 +234,12 @@ public bool ToolbarSeparatorRight
...
+            .ObserveOnDispatcher().Subscribe(OnRevealTransfer));
```
Comment (AliveDevil) [inline windows/src/main/csharp/ch/cyberduck/ui/ViewModels/TransfersViewModel.cs:242]: UI Thread synchronization required

File: windows/src/main/csharp/ch/cyberduck/ui/controller/TransferController.cs [hunk 3]
```diff
@@ -318,6 +320,8 @@ void TransferListener.transferDidStart(Transfer t)
             }
 
             progress.Refresh(null);
+
+            RevealTransfer?.Invoke(t);
```
Comment (AliveDevil) [inline windows/src/main/csharp/ch/cyberduck/ui/controller/TransferController.cs:324]: Each started transfer should allow the UI to select that transfer.

**Review by ylangisc — APPROVED** [review]
